const firstSemester = {
  pdfUrl: "Civil_1st_Sem_Syllabus_New.pdf",
  subjects: [
    {
      code: "CHM 110",
      name: "Applied Chemistry",
      examType: "Both",
      theory: 80,
      practical: 20,
      total: 100,
      details: "",
      pages: [1, 4],
    },
    {
      code: "PHY 110",
      name: "Applied Physics",
      examType: "Both",
      theory: 80,
      practical: 20,
      total: 100,
      details: "",
      pages: [5, 9],
    },
    {
      code: "MTH 110",
      name: "Calculus I",
      examType: "Theory",
      theory: 100,
      practical: 0,
      total: 100,
      details: "",
      pages: [10, 13],
    },
    {
      code: "ENG 110",
      name: "Communication Techniques",
      examType: "Theory",
      theory: 100,
      practical: 0,
      total: 100,
      details: "",
      pages: [14, 17],
    },
    {
      code: "CMP 112",
      name: "Computer Programming",
      examType: "Both",
      theory: 80,
      practical: 20,
      total: 100,
      details: "",
      pages: [18, 22],
    },
    {
      code: "MEC 112",
      name: "Engineering Drawing",
      examType: "Practical",
      theory: 0,
      practical: 100,
      total: 100,
      details: "",
      pages: [23, 26],
    },
  ],
};

export default firstSemester;
